import{a as L,S as v,i as n}from"./assets/vendor-DaWAOjWS.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&u(f)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const w="52591555-089c8d48efe1c098578f49548",E="https://pixabay.com/api/",y=15;async function h(e,o=1){const t={key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:y};return(await L.get(E,{params:t})).data}const a={gallery:document.getElementById("gallery"),loadMoreBtn:document.getElementById("load-more"),loader:document.getElementById("loader")},B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(e){if(!Array.isArray(e)||e.length===0)return;const o=e.map(t=>`
        <div class="photo-card">
        <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="info">
            <p class="info-item"><b>Likes</b><span>${t.likes}</span></p>
            <p class="info-item"><b>Views</b><span>${t.views}</span></p>
            <p class="info-item"><b>Comments</b><span>${t.comments}</span></p>
            <p class="info-item"><b>Downloads</b><span>${t.downloads}</span></p>
        </div>
        </div>
    `).join("");a.gallery.insertAdjacentHTML("beforeend",o),B.refresh()}function A(){a.gallery.innerHTML=""}function g(){a.loader.classList.add("visible")}function d(){a.loader.classList.remove("visible")}function b(){a.loadMoreBtn.classList.remove("hidden")}function l(){a.loadMoreBtn.classList.add("hidden")}const M=document.getElementById("search-form"),I=document.getElementById("search-input"),P=a.loadMoreBtn,S=a.gallery;let m="",i=1,c=0;M.addEventListener("submit",$);P.addEventListener("click",q);async function $(e){e.preventDefault();const o=I.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search query."});return}m=o,i=1,c=0,A(),l();try{g();const t=await h(m,i);if(d(),!t||!Array.isArray(t.hits)||t.hits.length===0){n.info({title:"No results",message:"No images found. Try another query."});return}p(t.hits),c=t.totalHits,i*y<c?b():(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),n.success({title:"Success",message:`Found ${c} images.`})}catch(t){d(),console.error(t),n.error({title:"Error",message:"Something went wrong. Please try again later."})}}async function q(){i+=1,l(),g();try{const e=await h(m,i);if(d(),!e||!Array.isArray(e.hits)||e.hits.length===0){l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}p(e.hits),O(),i*y>=e.totalHits?(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):b()}catch(e){d(),console.error(e),n.error({title:"Error",message:"Failed to load more images."})}}function O(){const e=S.querySelector(".photo-card");if(!e)return;const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
